version: 0.2
env:
  #secrets-manager:
  #  SPECTRAL_DSN: "MySecrets:SPECTRAL_DSN"
phases:
  build:
    commands:
      - curl -L "https://get.spectralops.io/latest/x/sh?dsn=$SPECTRAL_DSN" | sh
      - $HOME/.spectral/spectral scan
